plugin: rest

resources:
  - method: GET
    path: /integrations/overview
    response:
      statusCode: 200
      headers:
        'Content-Type': 'application/json'
      content: |
        {
          "data": {
            "affected_items": [
              { "id": "integration_1",  "name": "Integration 1",  "decoders_count": 5,  "kvdbs_count": 3 },
              { "id": "integration_2",  "name": "Integration 2",  "decoders_count": 4,  "kvdbs_count": 5 },
              { "id": "integration_3",  "name": "Integration 3",  "decoders_count": 7,  "kvdbs_count": 2 },
              { "id": "integration_4",  "name": "Integration 4",  "decoders_count": 2,  "kvdbs_count": 8 },
              { "id": "integration_5",  "name": "Integration 5",  "decoders_count": 6,  "kvdbs_count": 6 },
              { "id": "integration_6",  "name": "Integration 6",  "decoders_count": 3,  "kvdbs_count": 4 },
              { "id": "integration_7",  "name": "Integration 7",  "decoders_count": 8,  "kvdbs_count": 1 },
              { "id": "integration_8",  "name": "Integration 8",  "decoders_count": 9,  "kvdbs_count": 7 },
              { "id": "integration_9",  "name": "Integration 9",  "decoders_count": 1,  "kvdbs_count": 9 },
              { "id": "integration_10", "name": "Integration 10", "decoders_count": 10, "kvdbs_count": 10 },
              { "id": "integration_11", "name": "Integration 11", "decoders_count": 4,  "kvdbs_count": 2 },
              { "id": "integration_12", "name": "Integration 12", "decoders_count": 5,  "kvdbs_count": 7 },
              { "id": "integration_13", "name": "Integration 13", "decoders_count": 6,  "kvdbs_count": 3 },
              { "id": "integration_14", "name": "Integration 14", "decoders_count": 7,  "kvdbs_count": 5 },
              { "id": "integration_15", "name": "Integration 15", "decoders_count": 8,  "kvdbs_count": 4 },
              { "id": "integration_16", "name": "Integration 16", "decoders_count": 9,  "kvdbs_count": 6 },
              { "id": "integration_17", "name": "Integration 17", "decoders_count": 2,  "kvdbs_count": 1 },
              { "id": "integration_18", "name": "Integration 18", "decoders_count": 3,  "kvdbs_count": 2 },
              { "id": "integration_19", "name": "Integration 19", "decoders_count": 4,  "kvdbs_count": 3 },
              { "id": "integration_20", "name": "Integration 20", "decoders_count": 5,  "kvdbs_count": 4 },
              { "id": "integration_21", "name": "Integration 21", "decoders_count": 6,  "kvdbs_count": 5 },
              { "id": "integration_22", "name": "Integration 22", "decoders_count": 7,  "kvdbs_count": 6 },
              { "id": "integration_23", "name": "Integration 23", "decoders_count": 8,  "kvdbs_count": 7 },
              { "id": "integration_24", "name": "Integration 24", "decoders_count": 9,  "kvdbs_count": 8 },
              { "id": "integration_25", "name": "Integration 25", "decoders_count": 10, "kvdbs_count": 9 },
              { "id": "integration_26", "name": "Integration 26", "decoders_count": 1,  "kvdbs_count": 10 },
              { "id": "integration_27", "name": "Integration 27", "decoders_count": 2,  "kvdbs_count": 9 },
              { "id": "integration_28", "name": "Integration 28", "decoders_count": 3,  "kvdbs_count": 8 },
              { "id": "integration_29", "name": "Integration 29", "decoders_count": 4,  "kvdbs_count": 7 },
              { "id": "integration_30", "name": "Integration 30", "decoders_count": 5,  "kvdbs_count": 6 },
              { "id": "integration_31", "name": "Integration 31", "decoders_count": 6,  "kvdbs_count": 5 },
              { "id": "integration_32", "name": "Integration 32", "decoders_count": 7,  "kvdbs_count": 4 },
              { "id": "integration_33", "name": "Integration 33", "decoders_count": 8,  "kvdbs_count": 3 },
              { "id": "integration_34", "name": "Integration 34", "decoders_count": 9,  "kvdbs_count": 2 },
              { "id": "integration_35", "name": "Integration 35", "decoders_count": 10, "kvdbs_count": 1 },
              { "id": "integration_36", "name": "Integration 36", "decoders_count": 2,  "kvdbs_count": 2 },
              { "id": "integration_37", "name": "Integration 37", "decoders_count": 3,  "kvdbs_count": 3 },
              { "id": "integration_38", "name": "Integration 38", "decoders_count": 4,  "kvdbs_count": 4 },
              { "id": "integration_39", "name": "Integration 39", "decoders_count": 5,  "kvdbs_count": 5 },
              { "id": "integration_40", "name": "Integration 40", "decoders_count": 6,  "kvdbs_count": 6 },
              { "id": "integration_41", "name": "Integration 41", "decoders_count": 7,  "kvdbs_count": 7 },
              { "id": "integration_42", "name": "Integration 42", "decoders_count": 8,  "kvdbs_count": 8 },
              { "id": "integration_43", "name": "Integration 43", "decoders_count": 9,  "kvdbs_count": 9 },
              { "id": "integration_44", "name": "Integration 44", "decoders_count": 10, "kvdbs_count": 10 },
              { "id": "integration_45", "name": "Integration 45", "decoders_count": 1,  "kvdbs_count": 1 },
              { "id": "integration_46", "name": "Integration 46", "decoders_count": 2,  "kvdbs_count": 3 },
              { "id": "integration_47", "name": "Integration 47", "decoders_count": 3,  "kvdbs_count": 5 },
              { "id": "integration_48", "name": "Integration 48", "decoders_count": 4,  "kvdbs_count": 7 },
              { "id": "integration_49", "name": "Integration 49", "decoders_count": 5,  "kvdbs_count": 9 },
              { "id": "integration_50", "name": "Integration 50", "decoders_count": 6,  "kvdbs_count": 10 }
            ],
            "total_affected_items": 50
          }
        }
  - method: GET
    path: /integrations/decoders
    response:
      statusCode: 200
      headers:
        'Content-Type': 'application/json'
      content: |
        {
          "data": {
            "affected_items": [
              { "id": "decoder_1",  "name": "Decoder 1", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_2",  "name": "Decoder 2", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_3",  "name": "Decoder 3", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_4",  "name": "Decoder 4", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_5",  "name": "Decoder 5", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_6",  "name": "Decoder 6", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_7",  "name": "Decoder 7", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_8",  "name": "Decoder 8", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_9",  "name": "Decoder 9", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_10", "name": "Decoder 10", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_11", "name": "Decoder 11", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_12", "name": "Decoder 12", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_13", "name": "Decoder 13", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_14", "name": "Decoder 14", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_15", "name": "Decoder 15", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_16", "name": "Decoder 16", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_17", "name": "Decoder 17", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_18", "name": "Decoder 18", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_19", "name": "Decoder 19", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_20", "name": "Decoder 20", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_21", "name": "Decoder 21", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_22", "name": "Decoder 22", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_23", "name": "Decoder 23", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_24", "name": "Decoder 24", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_25", "name": "Decoder 25", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_26", "name": "Decoder 26", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_27", "name": "Decoder 27", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_28", "name": "Decoder 28", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_29", "name": "Decoder 29", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_30", "name": "Decoder 30", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_31", "name": "Decoder 31", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_32", "name": "Decoder 32", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_33", "name": "Decoder 33", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_34", "name": "Decoder 34", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_35", "name": "Decoder 35", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_36", "name": "Decoder 36", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_37", "name": "Decoder 37", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_38", "name": "Decoder 38", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_39", "name": "Decoder 39", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_40", "name": "Decoder 40", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_41", "name": "Decoder 41", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_42", "name": "Decoder 42", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_43", "name": "Decoder 43", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_44", "name": "Decoder 44", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_45", "name": "Decoder 45", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_46", "name": "Decoder 46", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_47", "name": "Decoder 47", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_48", "name": "Decoder 48", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_49", "name": "Decoder 49", "integration": "Integration", "space": "wazuh"},
              { "id": "decoder_50", "name": "Decoder 50", "integration": "Integration", "space": "wazuh"}
            ],
            "total_affected_items": 50
          }
        }
  - method: GET
    path: /content/asset/wazuh/decoder_1
    response:
      statusCode: 200
      headers:
        'Content-Type': 'application/json'
      content: |
        {
          "data": {
            "content": "id: decoder_1\nname: Decoder 1"
          }
        }
  - method: GET
    path: /integrations/kvdbs
    response:
      statusCode: 200
      headers:
        'Content-Type': 'application/json'
      content: |
        {
          "data": {
            "affected_items": [
              { "id": "kvdb_1",  "name": "KVDB 1",  "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_2",  "name": "KVDB 2",  "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_3",  "name": "KVDB 3",  "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_4",  "name": "KVDB 4",  "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_5",  "name": "KVDB 5",  "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_6",  "name": "KVDB 6",  "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_7",  "name": "KVDB 7",  "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_8",  "name": "KVDB 8",  "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_9",  "name": "KVDB 9",  "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_10", "name": "KVDB 10", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_11", "name": "KVDB 11", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_12", "name": "KVDB 12", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_13", "name": "KVDB 13", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_14", "name": "KVDB 14", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_15", "name": "KVDB 15", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_16", "name": "KVDB 16", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_17", "name": "KVDB 17", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_18", "name": "KVDB 18", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_19", "name": "KVDB 19", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_20", "name": "KVDB 20", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_21", "name": "KVDB 21", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_22", "name": "KVDB 22", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_23", "name": "KVDB 23", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_24", "name": "KVDB 24", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_25", "name": "KVDB 25", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_26", "name": "KVDB 26", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_27", "name": "KVDB 27", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_28", "name": "KVDB 28", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_29", "name": "KVDB 29", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_30", "name": "KVDB 30", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_31", "name": "KVDB 31", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_32", "name": "KVDB 32", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_33", "name": "KVDB 33", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_34", "name": "KVDB 34", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_35", "name": "KVDB 35", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_36", "name": "KVDB 36", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_37", "name": "KVDB 37", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_38", "name": "KVDB 38", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_39", "name": "KVDB 39", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_40", "name": "KVDB 40", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_41", "name": "KVDB 41", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_42", "name": "KVDB 42", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_43", "name": "KVDB 43", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_44", "name": "KVDB 44", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_45", "name": "KVDB 45", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_46", "name": "KVDB 46", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_47", "name": "KVDB 47", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_48", "name": "KVDB 48", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_49", "name": "KVDB 49", "integration": "Integration", "space": "wazuh" },
              { "id": "kvdb_50", "name": "KVDB 50", "integration": "Integration", "space": "wazuh" }
            ],
            "total_affected_items": 50
          }
        }
