hosts:
  - manager:
      url: 'https://wazuh.manager'
      port: 55000
      username: wazuh-wui
      password: MyS3cr37P450r.*-
      run_as: false
  - imposter:
      url: 'http://imposter'
      port: 8080
      username: wazuh-wui
      password: MyS3cr37P450r.*-
      run_as: false
  - imposter-cli:
      url: 'http://<ip-local>'
      port: 8080
      username: wazuh-wui
      password: MyS3cr37P450r.*-
      run_as: false
  - manager-dev:
      url: 'https://wazuh.manager.dev'
      port: 55000
      username: wazuh-wui
      password: wazuh-wui
      run_as: false

wazuh.updates.disabled: true
